#!/bin/bash
# Play tracks / radio from a CSV in PLAYLIST_FOLDER.
#
# Usage:
# 
# playlist ls                           --> list available playlists
# playlist <playlist_name>              --> play PLAYLIST_FOLDER/<playlist_name>.csv
# playlist <playlist_name> --no-shuffle --> turn off random order

# Check if PLAYLIST_FOLDER is set
if [ -z "$PLAYLIST_FOLDER" ]; then
    echo "Error: PLAYLIST_FOLDER environment variable is not set."
    exit 1
fi

# Function to list available playlists
list_playlists() {
    echo "Available playlists:"
    ls -1 "$PLAYLIST_FOLDER"/*.csv | xargs -n 1 basename | sed 's/\.csv$//' | sed 's/^/- /'
}

# Check for the correct number of arguments
if [ $# -eq 0 ] || [ $# -gt 2 ]; then
    echo "Usage: $0 <playlist_name> [--no-shuffle]"
    echo "       $0 ls"
    exit 1
fi

# Handle 'ls' command
if [ "$1" = "ls" ]; then
    list_playlists
    exit 0
fi

playlist_name="$1"
playlist_file="$PLAYLIST_FOLDER/${playlist_name}.csv"
shuffle_option="--shuffle"

# Check for shuffle option
if [ "$2" = "--no-shuffle" ]; then
    shuffle_option=""
fi

if [ ! -f "$playlist_file" ]; then
    echo "Playlist file not found: $playlist_file"
    exit 1
fi

# Extract YouTube URLs from the CSV and play them with mpv
awk -F ',' '{print $4}' "$playlist_file" \
    | xargs mpv --no-video \
                --osd-level=3 \
                --force-window=no \
                --osd-duration=99999 \
                --term-osd-bar \
                --term-osd=force \
                --term-playing-msg='${playlist-pos-1}/${playlist-count} - ${media-title}' \
                $shuffle_option
